config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :contacts
  resources :lists do
    get 'contact/nombre', to: 'contacts#nombre'
    collection do
      get 'contact/nombre', to: 'contacts#nombre'
    end
  end
  match 'contact/nombre', to: 'contacts#nombre', via: :get
  get 'send_sms/index', to: 'send_sms#index'
  get 'send_sms/send_sms', to: 'send_sms#send_sms'
  get 'send_sms/contact/nombre', to: 'contacts#nombre'
  get 'send_sms/list/descripcion', to: 'lists#descripcion'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :numero, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
	validates :nombre, presence: true
	has_many :list_contacts, dependent: :destroy
  	accepts_nested_attributes_for :list_contacts, allow_destroy: true
end

app/models/list_contact.rb
class ListContact < ActiveRecord::Base
  belongs_to :list
  belongs_to :contact
  LISTA = 1
  CONTACTO = 2

  def self.agrupar
  	[{id: self::LISTA, text: 'Lista de Contactos'}, {id: self::CONTACTO, text: 'Contactos Individuales'}]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:new, :show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    render template: 'contacts/form', layout: 'layouts/application'
  end

  # GET /contacts/1/edit
  def edit
    render template: 'contacts/form', layout: 'layouts/application'
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render template: 'contacts/form', layout: 'layouts/application' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render template: 'contacts/form', layout: 'layouts/application' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def nombre
    nombre = '---'
    if params[:contact_id].present? && params[:contact_id].to_i > 0
      nombre = Contact.find(params[:contact_id].to_i).try(:nombre) || '---'
    end
    render json: {nombre: nombre}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      if params[:id].present?
        @contact = Contact.find(params[:id])
        @url = contact_path(@contact)
      else
        @contact = Contact.new
        @url = contacts_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:nombre, :numero)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:new, :show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    render template: 'lists/form', layout: 'layouts/application'
  end

  # GET /lists/1/edit
  def edit
    render template: 'lists/form', layout: 'layouts/application'
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render template: 'lists/form', layout: 'layouts/application' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render template: 'lists/form', layout: 'layouts/application' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def descripcion
    descripcion = '---'
    if params[:list_id].present? && params[:list_id].to_i > 0
      descripcion = List.find(params[:list_id].to_i).try(:descripcion) || '---'
    end
    render json: {descripcion: descripcion}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      if params[:id].present?
        @list = List.find(params[:id])
        @url = list_path(@list)
      else
        @list = List.new
        @url = lists_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:nombre, :descripcion, list_contacts_attributes: [:id, :list_id, :contact_id, :_destroy])
    end
end

app/controllers/send_sms_controller.rb
class SendSmsController < ApplicationController
	require Rails.root.join('lib', 'venbrain.rb').to_s

	before_action :authenticate_user!, except: :index

	def index
		render template: 'send_sms/form', layout: 'layouts/application'
	end

	def send_sms
		contacts = []
		case params[:agrupar].to_i
		when ListContact::LISTA
			if params[:list_contacts].present?
				params[:list_contacts].each do |param_list|
					if List.exists?(param_list.second[:list_id].to_i)
						contacts += List.find(param_list.second[:list_id].to_i).list_contacts.joins(:contact).pluck(:numero)
					end
				end
			end
		when ListContact::CONTACTO
			if params[:contacts].present?
				params[:contacts].each do |params_contact|
					if Contact.exists?(params_contact.second[:contact_id].to_i)
						contacts << Contact.find(params_contact.second[:contact_id].to_i).try(:numero)
					end
				end
			end
		end
		contacts = contacts.compact.uniq
		mensaje = params[:mensaje]
		if mensaje.blank?
			flash[:alert] = 'El mensaje se encuentra vacio, agregue un mensaje e intente nuevamente'
			render template: 'send_sms/form', layout: 'layouts/application'
		elsif contacts.blank?
			flash[:alert] = 'No existen numero de contactos en los datos, revise sus datos e intente nuevamente'
			render template: 'send_sms/form', layout: 'layouts/application'
		else
			enviados = Venbrain.send('send_multi_sms', contacts, mensaje)
			flash[:notice] = "Se envio el mensaje a #{enviados}/#{contacts.count} contactos"
			redirect_to action: :index
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact_form.html.erb
<%= render partial: 'shared/errors_messages_detail',
  locals: { record: record, items_errors: [:base, :detalle] }
%>
<div class="small-12 large-12 column">
  <div class="row">
    <div class="panel small-12 medium-10 large-6 columns">
      <div class='panel-title light-blue small-12'>
        <span>Contacto</span>
      </div>
      <div class="panel-content row">
        <div class="small-12 columns">
          <div class="large-10 small-12 medium-12 colums end">
            <%= render partial: 'inputs/text_field', layout: 'layouts/input',
              locals: {
                model: model, label_text: 'Nombre', field: :nombre,
                object: record
              }
            %>
            <%= render partial: 'inputs/number_field', layout: 'layouts/input',
              locals: {
                model: model, label_text: 'Numero*', field: :numero,
                object: record
              }
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/form.html.erb
<div class="small-12 medium-12 large-12 column">
  <%= render partial: 'shared/flash_messages', locals: {flash: flash} %>
  <%=
    render partial: 'contacts/contact_form', layout: "layouts/form",
           locals: {
             record: @contact,
             model: :contact,
             url: @url
           }
  %>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="columns small-12 large-12 large-centered">
    <%= link_to "Nuevo Contacto", new_contact_path, class: "button black" %>
    <%= link_to "Listas De Contactos", lists_path, class: "button black" %>
    <%= link_to "Enviar SMS", send_sms_index_path, class: "button black" %>
    <table id="lists" class="table" border="0" cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th colspan="2">
            Contactos
          </th>
          <th class="action_column" />
        </tr>
        <tr>
          <th>Nombre</th>
          <th>Número</th>
          <th class="action_column" />
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr id="contact_<%= contact.id %>">
            <td><%= contact.try(:nombre) || '---' %></td>
            <td><%= contact.try(:numero) %></td>
            <td class="action_column">
              <div class="action_links" >
                <%= link_to "", contact, :class => "fa fa-search view_link" %>
                <%= link_to "", edit_contact_path(contact), class: 'fa fa-pencil edit_link' %>
                <%= link_to "",  contact, method: :delete, class: 'fa fa-trash delete_link', data: { confirm: '¿Está seguro de que quiere eliminar esto?'} %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="row">
  <%= link_to 'Atras', contacts_path, class: 'button black' %>
  <%= link_to 'Editar', edit_contact_path(@contact), class: 'button black' %>
</div>
<div class="row">
  <div class='panel large-8 columns'>
    <div class='panel-title light-blue small-12'>
      <span>Contacto</span>
    </div>
    <div class='panel-content row'>
      <div class='small-12 large-12 columns'>
        <table id="contact" class="table" border="0" cellpadding="0" cellspacing="0">
          <thead>
            <tr>
              <th colspan="2">
                Contactos
              </th>
            </tr>
            <tr>
              <th>Nombre</th>
              <th>Número</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @contact.try(:nombre) || '---' %></td>
              <td><%= @contact.try(:numero) %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/inputs/_chosen.erb
<%
  include_blank ||= '--- Seleccione una opción ---'
  multiple ||= false
  data ||= ''
  collection ||= []
  selected ||= nil
  disabled ||= false
%>
<%= select(model, field, collection, {include_blank: include_blank, selected: selected},
  {multiple: multiple, data: data, class: 'chosen', disabled: disabled })
%>

app/views/inputs/_chosen_ajax_tag.html.erb
<%
  name_prefix ||= ''
  options ||= ''
  clases ||= ''
  data = data.merge({'select-type' => 'chosen-ajax'})
%>
<%= select_tag(name_prefix, options, class: clases, data: data) %>

app/views/inputs/_chosen_tag.html.erb
<%
  name_prefix ||= ''
  options ||= ''
  clases ||= ''
  data = data.merge({'select-type' => 'chosen'})
  prompt ||= '--- Selecciones una opción ---'
%>
<%= select_tag(name_prefix, options, class: "#{clases} chosen".squish, data: data, prompt: prompt) %>

app/views/inputs/_email_field.html.erb
<% data ||= ''%>
<%= email_field(model, field, data: data) %>

app/views/inputs/_hidden.html.erb
<%= hidden_field(model, field, value: value) %>

app/views/inputs/_hidden_field_tag.html.erb
<%
  name_prefix ||= ''
  value ||= ''
  clases ||= ''
  data ||= ''
  disabled ||= false
  readonly ||= false
%>

<%= hidden_field_tag(name_prefix, value, class: clases, data: data,
                     disabled: disabled, readonly: readonly)
%>

app/views/inputs/_number_field.html.erb
<% data ||= ''
  readonly ||= nil
  value ||= object.send(field)
%>
<%= number_field(model, field, data: data, value: value) %>

app/views/inputs/_password_field.html.erb
<% data ||= ''%>
<%= password_field(model, field, data: data) %>

app/views/inputs/_select.html.erb
<%
  include_blank ||= false
  multiple ||= false
  data ||= ''
  choosen ||= ''
  prompt ||= nil
  collection ||= []
%>
<%=select(model, field, collection, {include_blank: include_blank, prompt: prompt},
  {multiple: multiple, data: data, class: choosen})
%>

app/views/inputs/_text_area_field.html.erb
<% data ||= ''
  readonly ||= nil
  value ||= object.send(field)
%>
<%= text_area(model, field, data: data, readonly: readonly, value: value) %>

app/views/inputs/_text_field.html.erb
<% data ||= ''
  readonly ||= nil
  value ||= object.send(field)
%>
<%= text_field(model, field, data:data, readonly: readonly, value: value) %>

app/views/inputs/_text_field_tag.html.erb
<%
  name_prefix ||= ''
  value ||= ''
  clases ||= ''
  data ||= ''
  disabled ||= false
  readonly ||= false
%>

<%= text_field_tag(name_prefix, value, class: clases, data: data,
                   disabled: disabled, readonly: readonly)
%>

app/views/layouts/_form.html.erb
<%= form_for(record, url: url ) do |f| %>
  <%= yield %>
  <div class="actions input_action">
    <%= f.submit "Guardar", class: "button black" %>
    <%= link_to "Cancelar", url, class: "button black cancel" %>
  </div>
<% end %>

app/views/layouts/_input.html.erb
<%
  field_error = object.errors[field].first || ""
  clases = "#{clases}"
  position ||= 'default'
  moneda ||= nil
  object_name = ActiveModel::Naming.param_key(object)
  object_id = [object_name, field.to_s, 'input'].join('_')
%>
<% if position == 'default' && moneda.blank? %>
  <div class="row <%= clases %>" id="<%= object_id %>">
    <div class="small-5 column field-label">
      <%= label model, field, label_text, class: "right label" %>
    </div>
    <div class="small-7 column field-input">
      <%= yield %>
      <span class="inline-errors"><%=field_error.humanize %></span>
    </div>
  </div>
<% elsif position == 'default' && moneda.present? %>
    <div class="row <%= clases %>" id="<%= object_id %>">
    <div class="small-5 column field-label">
      <%= label model, field, label_text, class: "right label" %>
    </div>
    <div class="small-7 column postfix-round field-input">
      <div class="row collapse <%= clases %>">
        <div class="small-2 columns">
          <span class="prefix"><%= moneda %></span>
        </div>
        <div class="small-10 columns">
          <%= yield %>
          <span class="inline-errors"><%=field_error.humanize %></span>
        </div>
      </div>
    </div>
  </div>
<% else %>
    <div class="row <%= clases %>" id="<%= object_id %>">
    <div class="small-2 column field-input">
      <%= yield %>
      <span class="inline-errors"><%=field_error.humanize %></span>
    </div>
    <div class="small-10 column field-label">
      <%= label model, field, label_text, class: "right label" %>
    </div>
  </div>
<% end %>

app/views/layouts/_input_tag.html.erb
<%
  clases = clases || ''
  name_prefix ||= ''
  msg_error ||= nil
%>
<div class="row">
  <div class="small-5 columns field-label show-on-med-and-down hide-on-large">
    <%=label_tag(name_prefix, label_text, class: "has-many-label right label") %>
  </div>
  <div class="small-7 large-12 columns field-input ">
    <%= yield %>
    <% if msg_error.present? %>
      <span class="inline-errors"><%= msg_error %></span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">INICIO</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li>
            <%= link_to 'Contactos', contacts_path %>
          </li>
          <li>
            <%= link_to 'Listas', lists_path %>
          </li>
          <li class="has-dropdown">
            <a href="#"><%= current_user.email %></a>
            <ul class="dropdown">
              <li> <%= link_to 'Salir', destroy_user_session_path, method: :delete  %> </li>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/lists/_list_contacts_form.html.erb
<% template_name = "list_contacts_items" %>
<div class="row">
  <div class='panel small-12 medium-10 large-6 columns'>
    <div class='panel-title light-blue small-12 medium-12 large-12'>
      <span>Contactos</span>
    </div>
    <div class='panel-content has_many'>
      <div class='headers hide-on-med-and-down'>
        <div class='row'>
          <div class='large-2 columns'><span>Nº</span></div>
          <div class='large-4 columns'><span>Numero</span></div>
          <div class='large-4 columns'><span>Nombre</span></div>
        </div>
      </div>
      <div id="<%= template_name %>" class='has-many-items'>
        <% record.list_contacts.each_with_index do |detail, i| %>
          <%= render 'lists/list_contacts_item_form', item_number: i + 1, is_template: false,
            record: record, detail: detail, is_new_record: false
          %>
        <% end %>
      </div>
      <div class='row'>
        <a href='#' class='add-has_many fa fa-plus' data-target-id="<%= template_name %>" id="add-<%= template_name %>"></a>
      </div>
      <div id="<%= template_name %>_template" style='display:none;'>
        <%= render 'lists/list_contacts_item_form', item_number: nil,
            is_template: true, detail: nil, record: record, is_new_record: false
        %>
      </div>
    </div>
  </div>
</div>

app/views/lists/_list_contacts_item_form.html.erb
<%
  item_number ||= '_item-number_'
  name = "list[list_contacts_attributes][#{item_number}]"
  msg = Hash.new
  if is_template
    template_input_class = "template_input"
    name_prefix = ""
    data = name
  else
    template_input_class = ""
    name_prefix = name
    data = ""
  end
  if detail.present?
    id = detail.id
    nombre = detail.contact.try(:nombre)
    contact_id = detail.contact_id
    if detail.present? && detail.errors.present?
      detail.errors.keys.each do |key|
        msg[key] =  detail.errors.messages[key].first.humanize
      end
    end
  else
    id = nombre = contact_id = nil
  end
%>
<div class="has_many has_many-item" data-item-number="<%=item_number%>" id="list_contact_<%=item_number%>">
  <div class="row">
    <div class="small-12 medium-12 large-2 columns item-number inputs">
      <input type="text" class="item-number" name="item_number" value="<%=item_number%>" disabled>
    </div>
    <div class="small-12 medium-12 large-4 columns inputs">
      <%= render partial: 'inputs/chosen_tag', layout: 'layouts/input_tag',
        locals: {
          name_prefix: "#{name_prefix}[contact_id]", label_text: 'Numero',
          options: options_from_collection_for_select(Contact.all, :id, :numero, contact_id),
          clases: [template_input_class, 'contact_id'].join(' '), msg_error: msg[:contact_id],
          data: {
            template_name: "#{data}[contact_id]",
            'placeholder' => '--- Numero ---'
          }
        }
      %>
    </div>
    <div class="small-12 medium-12 large-4 columns inputs">
      <%= render partial: "inputs/text_field_tag", layout: 'layouts/input_tag',
        locals: {
          name_prefix: "#{name_prefix}[nombre]", label_text: 'Nombre', value: nombre,
          clases: template_input_class + " nombre",
          data: {
            template_name: "#{data}[nombre]",
            readonly: true, disabled: true
          }
        }
      %>
    </div>
    <div class="inputs">
      <%= render partial: "inputs/hidden_field_tag",
        locals: {
          name_prefix: "#{name_prefix}[id]", value: id,
          clases: template_input_class + " id",
          data: {
            template_name: "#{data}[id]"
          }
        }
      %>
    </div>
    <% unless is_new_record %>
      <div class='small-12 medium-12 large-1 columns inputs end delete'>
        <% if is_template %>
          <a class="delete-has_many fa fa-close"></a>
        <% else %>
          <div class="delete-has_many-checkbox">
            <%= hidden_field_tag("#{name_prefix}[_destroy]", "0") %>
            <%=check_box_tag("#{name_prefix}[_destroy]", "1")%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/_list_form.html.erb
<%= render partial: 'shared/errors_messages_detail',
  locals: { record: record, items_errors: [:base, :detalle] }
%>
<div class="small-12 large-12 column">
  <div class="row">
    <div class="panel small-12 medium-10 large-6 columns">
      <div class='panel-title light-blue small-12'>
        <span>Lista De Contactos</span>
      </div>
      <div class="panel-content row">
        <div class="small-12 columns">
          <div class="large-10 small-12 medium-12 colums end">
            <%= render partial: 'inputs/text_field', layout: 'layouts/input',
              locals: {
                model: model, label_text: 'Nombre*', field: :nombre,
                object: record
              }
            %>
            <%= render partial: 'inputs/text_area_field', layout: 'layouts/input',
              locals: {
                model: model, label_text: 'Descripción', field: :descripcion,
                object: record
              }
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'lists/list_contacts_form', locals: {record: record} %>
</div>

app/views/lists/form.html.erb
<%= javascript_include_tag "venbrain/views/lists" %>
<div class="small-12 medium-12 large-12 column">
  <%= render partial: 'shared/flash_messages', locals: {flash: flash} %>
  <%=
    render partial: 'lists/list_form', layout: "layouts/form",
           locals: {
             record: @list,
             model: :list,
             url: @url
           }
  %>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="columns small-12 large-12 large-centered">
    <%= link_to "Nueva Lista", new_list_path, class: "button black" %>
    <%= link_to "Contactos", contacts_path, class: "button black" %>
    <%= link_to "Enviar SMS", send_sms_index_path, class: "button black" %>
    <table id="lists" class="table" border="0" cellpadding="0" cellspacing="0">
      <thead>
        <tr>
          <th colspan="2">
            Listas De Contactos
          </th>
          <th class="action_column" />
        </tr>
        <tr>
          <th>Nombre</th>
          <th>Descripción</th>
          <th class="action_column" />
        </tr>
      </thead>
      <tbody>
        <% @lists.each do |list| %>
          <tr id="list_<%= list.id %>">
            <td><%= list.try(:nombre) %></td>
            <td><%= list.try(:descripcion) %></td>
            <td class="action_column">
              <div class="action_links" >
                <%= link_to "", list, :class => "fa fa-search view_link" %>
                <%= link_to "", edit_list_path(list), class: 'fa fa-pencil edit_link' %>
                <%= link_to "",  list, method: :delete, class: 'fa fa-trash delete_link', data: { confirm: '¿Está seguro de que quiere eliminar esto?'} %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <%= link_to 'Atras', lists_path, class: 'button black' %>
  <%= link_to 'Editar', edit_list_path(@list), class: 'button black' %>
</div>
<div class="row">
  <div class='panel large-8 columns'>
    <div class='panel-title light-blue small-12'>
      <span>Lista De Contactos</span>
    </div>
    <div class='panel-content row'>
      <div class='small-12 large-12 columns'>
        <table id="list" class="table large-6" border="0" cellspacing="0" cellpadding="0">
          <thead>
          	<tr>
              <th colspan="2">
                Lista de Contactos
              </th>
            </tr>
            <tr>
              <th>Nombre</th>
              <th>Descripción</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @list.try(:nombre) %></td>
              <td><%= @list.try(:descripcion) || '---' %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class='panel large-8 columns'>
    <div class='panel-title light-blue small-12'>
      <span>Contactos En la Lista</span>
    </div>
    <div class='panel-content row'>
      <div class='small-12 large-12 columns'>
        <table id="contacts" class="table" border="0" cellpadding="0" cellspacing="0">
          <thead>
            <tr>
              <th colspan="2">
                Contactos
              </th>
            </tr>
            <tr>
              <th>Nombre</th>
              <th>Número</th>
            </tr>
          </thead>
          <tbody>
          	<% @list.list_contacts.each do |list_contact| %>
	            <tr>
	              <td><%= list_contact.contact.try(:nombre) || '---' %></td>
	              <td><%= list_contact.contact.try(:numero) %></td>
	            </tr>
	        <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/send_sms/_contacts_form.html.erb
<% template_name = "contacts_items" %>
<div id="partial_contacts" class="row hide">
  <div class='panel small-12 medium-10 large-8 columns'>
    <div class='panel-title light-blue small-12 medium-12 large-12'>
      <span>Contactos</span>
    </div>
    <div class='panel-content has_many'>
      <div class='headers hide-on-med-and-down'>
        <div class='row'>
          <div class='large-2 columns'><span>Nº</span></div>
          <div class='large-4 columns'><span>Número De Contacto </span></div>
          <div class='large-5 columns center'><span>Nombre</span></div>
        </div>
      </div>
      <div id="<%= template_name %>" class='has-many-items'>
      </div>
      <div class='row'>
        <a href='#' class='add-has_many fa fa-plus' data-target-id="<%= template_name %>" id="add-<%= template_name %>"></a>
      </div>
      <div id="<%= template_name %>_template" style='display:none;'>
        <%= render 'send_sms/contacts_item_form', item_number: nil,
          is_template: true, detail: nil, record: nil, is_new_record: false
        %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors_messages.html.erb
<div class="row">
  <div class="errors">
    <% errors.each do |msg| %>
      <div class="alert-box error">
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<div class="row">
  <div class="flashes small-12">
    <% flash.each do |name, msg| %>
      <div class="flash flash_<%=name%>">
        <%= msg %>
        <a></a>
      </div>
    <% end %>
  </div>
</div>